// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // tsx isn't usable here (its esbuild dependency's native binary is
    // blocked by this machine's Application Control Policy) — see README.
    seed: "node scripts/run-ts.mjs prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // Only used by `prisma migrate dev` for drift detection; optional.
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
